name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - afro-vintage-backend/**

  pull_request:
    branches:
      - main
    paths:
      - afro-vintage-backend/**

jobs:
  build-test-and-docker:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.0'

      # Install dependencies
      - name: Install dependencies
        working-directory: afro-vintage-backend
        run: go mod tidy

      # Run tests
      - name: Run tests
        working-directory: afro-vintage-backend
        run: go test ./... -v

      # Build Docker Image
      - name: Build Docker image
        working-directory: afro-vintage-backend
        run: docker build -t afro-vintage-backend:latest .
