name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - backend/afro-vintage-backend/**
  pull_request:
    branches:
      - main
    paths:
      - backend/afro-vintage-backend/**

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      # Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # Run tests
      - name: Run tests
        run: go test ./... -v
